### ISSUE TITLE
[RFC] Certificazione modulo

### ISSUE THREAD

**Issue by giogioppi** [link-it/govpay-stampe-api#9]
Buongiorno a tutti, 
non so se sia giusto aprire una issue per questo argomento ma non saprei dove altro scrivere. 

La domanda è : 
questo modulo e/o gli avvisi pdf che produce, sono in qualche modo certificati da PagoPa? 

Lo chiedo perché ho un dubbio che non riesco a sciogliere : 

- noi siamo una software house che fornisce ad un ente creditore una piattaforma gestionale.
  In genere, l’ente creditore è affiliato ad un partner tecnologico che ci consente di integrarci con i loro servizi web tramite cui inviamo 
  i pagamenti a pagopa (quindi partendo dal nostro gestionale invochiamo i servizi del PT che a sua volta gira il pagamento al Nodo).
  Come software house, NON siamo in alcun modo accreditati presso PagoPa né ci siamo mai interfacciati direttamente con i loro 
  sevizi.
  
  Adesso, un partner tecnologico di un ente, ha delegato a noi la produzione degli avvisi di pagamento pdf per i quali abbiamo, 
  appunto, deciso di utilizzare questo modulo.
  E’ una cosa possibile o bisogna fare un iter particolare per l’approvazione del pdf prodotto?

  In generale, Il partner tecnologico ha l’obbligo di fornire i servizi per consentire la comunicazione verso il nodo dei pagamenti (sia 
  che sia il download del pdf o il pagamento online) o è libero di delegarli all’ente cerditore o alla software house che fa da 
  intermediario tra l’ente e il partner?

Spero di essere riuscito a spiegarmi bene, se non sono stato chiaro chiedere pure.

Grazie per l'attenzione

**Comment by nardil** [comment]
Salve @giogioppi ,

pagoPA non certifica i software utilizzati per il collegamento alla piattaforma di pagamento, ma certifica i partner ed intermediari interconnessi. Non ci risultano procedure da dover seguire per realizzare quanto a voi necessario.

Il microservizio di stampa e' basato su quello incluso in [GovPay](https://github.com/link-it/govpay) che e' utilizzato con successo da diversi partner/intermediari, pertanto le stampe sono formalmente conformi alle specifiche. Consigliamo comunque una verifica sul campo che gli avvisi prodotti risultino correttamente pagabili.

Spero di aver risposto esaustivamente al questito, ma per eventuali chiarimenti sulle procedure pagoPA non documentate pubblicamente e' necessario chiedere direttamente a loro.

**Comment by giogioppi** [comment]
Grazie mille per il chiarimento @nardil! 

Sempre considerando che non siamo  partner tecnologici e che non ci siamo mai integrati con PagoPa, avrei un'altra domanda,, non so se puoi aiutarmi : 
- Un partner tecnologico con cui dobbiamo interfacciarci, ci ha chiesto di implementare in autonomia una chiamata alla nuova "checkout" di PagoPa perché loro non hanno un servizio richiamabile dall'esterno per fruirne. Possiamo chiamare "liberamente" la checkout di pagopa senza essere Partner Tecnologici e, quindi, senza un'autenticazione?

- Se si, ovvero se possiamo effettuare la chiamata, basta la chiamata al solo servizio di checkout oppure va implementato un workflow che effettui chiamate a diversi servizi? 

Grazie per l'attenzione.

**Comment by nardil** [comment]
Il servizio checkout non richiede autenticazione e fa parte del workflow di pagamento ad iniziativa EC di pagoPA: https://docs.pagopa.it/sanp/casi-duso/pagamento-presso-frontend-dellec

**Comment by giogioppi** [comment]
@nardil innanzi tutto grazie per la celere risposta. 

Prima di fare un'ulteriore domanda, cerco di spiegare un po' la nostra situazione: 
l'Ente Creditore si avvale di un Partner Tecnologico per gestire i pagamenti tramite PagoPa, però usa anche un nostro applicativo, tramite cui devono essere effettuati i pagamenti. 

In genere, noi ci interfacciamo con il Partner Tecnologico dell'ente, che ci mette a disposizione dei servizi (rest o soap) tramite cui mandiamo le informazioni del pagamento al PT che, a sua volta, interagisce con il nodo dei pagamenti. Quindi per noi è sempre stato tutto trasparente. 

Adesso, questo nuovo PT, ci chiede di implementare la checkout ed anche la produzione degli avvisi di pagamento PDF. 

Fatta la premessa, 
dal diagramma della checkout mi sembra di capire che il backend dell'ente creditore dovrebbe esporre due servizi - "paGetPayment" e "paSendRT"- con cui interagirà il nodo dei pagamenti. 

Ma questi servizi dovrebbero essere esposti dal Partner Tecnologico, giusto? 
E, se si, se noi chiamiamo la checkout dal nostro applicativo, il nodo saprà che deve chiamare quei servizi presso il PT o si aspetta che li esponiamo noi? 

Non so se sia riuscito a spiegarmi bene, in caso di dubbi domandate pure.

**Comment by nardil** [comment]
Ciao @giogioppi ,

in caso di integrazione sincrona, la componente `EC Backend` viene implementata dal partner/intermediario tecnologico, mentre nel caso sia utilizzata la modalita' asincrona, la componente e' assorbita da pagoPA: https://docs.pagopa.it/sanp/ente-creditore/modalita-dintegrazione

Solo in caso di connessione diretta a pagoPA (ovvero l'ente e' intermediario di se stesso) allora e' necessario implementare la componente `EC Backend` ed esporre i servizi da te citati verso pagoPA.

**Comment by giogioppi** [comment]
Buongiorno @nardil, 
sempre grazie per la risposta. 

Dunque, nel caso il PT chieda a noi di implementare ed esporre le funzioni da me citate, possiamo dirgli che non è compito nostro ma loro? 

E, un'ultima cosa, dove posso trovare l'url completo della checkout?  

[qui](https://docs.pagopa.it/sanp/ente-creditore/modalita-dintegrazione/integrazione-touch-point-dellec-con-checkout) dovrebbero esserci i parametri per la request e, se clicco sull'url "[POST](https://docs.pagopa.it/sanp/appendici/primitive#ec-checkout-api)", mi rimanda (quando l'url funziona, stamattina va un po' a singhiozzi) ad un pagina dove trovo un'API che si chiama _**/carts**_. E' questo il servizio da richiamare?

**Comment by nardil** [comment]
Ciao @giogioppi , 

> Dunque, nel caso il PT chieda a noi di implementare ed esporre le funzioni da me citate, possiamo dirgli che non è compito nostro ma loro?

questo dipende da cosa e' stato previsto nel contratto di intermediazione tra il PT e l'Ente. In linea di principio si.

> E, un'ultima cosa, dove posso trovare l'url completo della checkout?

Nella [pagina in cui viene descritta l'API](https://docs.pagopa.it/sanp/appendici/primitive#ec-checkout-api) c'e' indicata la URL dell'ambiente di UAT. Per la produzione e' sufficiente modificare l'host.

La issue e' andata OT, oltre che chiusa, ti chiedo di aprirne eventualmente un'altra in GovPay

**Comment by giogioppi** [comment]
va bene @nardil, 
scusa per il disturbo e grazie mille per il supporto e per la disponibilità. 

Un saluto
